version: '3.8'

services:
  fcs-um-fe:
    image: 'fcs-um-fe-server:v1'
    environment:
      - TZ=Asia/Kuala_Lumpur
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
    volumes:
      ##FOR PRODUCTION
      - /var/www/um/fe/frontend/build:/usr/share/nginx/html
      ##FOR DEVELOPMENT
      #   - ./build:/var/www/fe
    stop_grace_period: 15s
    restart: always
    networks:
      - marlin_group
#    ports:
#      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "30m"  # Limit log file to 50KB
        max-file: "10"    # Keep only 1 log file (delete old logs)


networks:
  marlin_group:
    external: true