
server {
    listen 80;
    server_name localhost;


    # Main SPA route
    location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                alias /var/www/fe/;
                index index.html index.htm index.nginx-debian.html;
    }

}